name: scientisst_db
description: Simple and powerful NoSQL document-based local database.
version: 0.0.4
homepage: https://scientisst.com
repository: https://github.com/scientisst/scientisst_db

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  watcher: ^0.9.7+15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
